package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Wednesday, May 13, 2026 9:55:09 PM IST
*/

public interface CalculatorOperations 
{
  float add (float a, float b);
  float sub (float a, float b);
  float mul (float a, float b);
  float div (float a, float b);
} // interface CalculatorOperations
